FROM node:alpine
WORKDIR '/app'

COPY package.json .
RUN npm install

RUN apk add chromium
ENV CHROME_BIN=/usr/bin/chromium-browser

COPY . .
EXPOSE 4200
CMD npm run start -- --host 0.0.0.0 --disableHostCheck true
