sudo: required
services:
    - docker

before_install:
    - docker build -t get2vj/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run get2vj/client-test npm test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI

after_success:
    - docker build -t get2vj/multi-client ./client
    - docker build -t get2vj/multi-nginx ./nginx
    - docker build -t get2vj/multi-server ./server
    - docker build -t get2vj/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push get2vj/multi-client
    - docker push get2vj/multi-nginx
    - docker push get2vj/multi-server
    - docker push get2vj/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-650397460025"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

